name: frontend
description: "Personal Android AI voice assistant with native device actions."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  record: ^7.1.1
  audio_stream_player: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
